services:
  apacheshib:
    image: dockerhub.csc.ncsu.edu/ignacioxd/apacheshib-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs:/var/log/apache2
    environment:
      - SERVER_NAME=example.ncsu.edu
      - LOGIN_PATH=/ # Make it so that all requests to the frontend are authenticated

  app: #frontend
    build: ./Dashboard
    restart: unless-stopped
    volumes:
      - ./Dashboard:/app/frontend/src
    environment:
      - PORT=80

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.test
    restart: "no"
    volumes:
      - ./backend/src:/app/src
    environment:
      - PORT=80
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: "mariadb:latest"
    volumes:
      - ./testDatabase/schema:/docker-entrypoint-initdb.d
      - ./testDatabase/data:/var/lib/mysql
    env_file:
      - .env # in root, configure db, backend, etc
    ports:
      - 3307:3306
